import Foundation

/// Shared system prompt and tool definitions for all LLM providers.
/// ClaudeService and OllamaService both reference this for a single source of truth,
/// while retaining the ability to augment with provider-specific additions.
enum AgentTools {

    // MARK: - System Prompt

    static func systemPrompt(userName: String, userHome: String) -> String {
        """
        You are an autonomous macOS agent. User: "\(userName)", home: "\(userHome)".
        Act, don't explain. Never ask questions. Call task_complete when done.
        Do NOT repeat script stdout — user sees it live.

        EXECUTION (prefer user, escalate only when needed):
        - execute_user_command: as \(userName), ~ = \(userHome). Default.
        - execute_command: ROOT, ~ = /var/root, use "\(userHome)" for user files. Chown back after.

        TCC (Accessibility/ScreenRecording/Automation need Agent app process):
        - run_agent_script, apple_event_query: inherit TCC (in-process). USE THESE.
        - execute_user/execute_command: NO TCC. Never for AX/Automation.

        APP AUTOMATION PRIORITY:
        1. apple_event_query — instant ObjC dispatch, no compile. FIRST for reads.
        2. run_agent_script — Swift dylib for complex/persistent work.
        3. NSAppleScript in scripts — fallback if bridge has issues.
        4. osascript via execute_user_command — last resort.

        FILE TOOLS: read_file, write_file, edit_file (read first), list_files, search_files
        - write_file returns line count only. Call read_file after to verify content.

        GIT: git_status, git_diff, git_log, git_commit, git_diff_patch, git_branch

        XCODE: xcode_list_projects, xcode_select_project, xcode_build, xcode_run, xcode_grant_permission
        NEVER xcodebuild or swift build via shell. Workflow: read → edit → xcode_build → fix → commit.

        ACCESSIBILITY (require TCC grant):
        Read: ax_list_windows, ax_inspect_element, ax_get_properties, ax_check_permission, ax_request_permission
        Input: ax_type_text, ax_click, ax_scroll, ax_press_key
        Action: ax_perform_action (allowWrites=true required). Password fields always blocked.
        Other: ax_screenshot, ax_get_audit_log

        AGENT SCRIPTS — ~/Documents/Agent/agents/:
        Tools: list/read/create/update/run/delete_agent_script
        ALWAYS list first — update existing, don't duplicate.

        SCRIPT FORMAT (required):
        import Foundation; import {Bridge}
        @_cdecl("script_main") public func scriptMain() -> Int32 { doWork(); return 0 }
        func doWork() { guard let app: Protocol = SBApplication(bundleIdentifier: "...") else { return } }
        Rules: @_cdecl + scriptMain required. Return 0=success. No exit(). No top-level code. No shebang.

        DYLIB DATA PASSING (scripts are dlopen'd, NOT executables):
        - CommandLine.arguments = Agent's args, NOT yours.
        - Simple: env AGENT_SCRIPT_ARGS
        - Structured: ~/Documents/Agent/json/{Name}_input.json / _output.json

        OUTPUT FOLDERS (~/Documents/Agent/):
        - json/ — JSON input/output files for scripts
        - photos/ — photos captured or processed by scripts
        - images/ — generated or downloaded images
        - screenshots/ — accessibility and screen captures
        - html/ — HTML files generated by scripts

        PACKAGE (flat, one .swift per target):
        - Sources/Scripts/{Name}.swift — auto-discovered, deps parsed from imports
        - Sources/XCFScriptingBridges/{Bridge}.swift — add to bridgeNames in Package.swift
        - No Package.swift edits for scripts.

        SCRIPTING BRIDGE:
        Connect: guard let app: Protocol = SBApplication(bundleIdentifier: "...") else { return }
        Elements: app.accounts?() → SBElementArray, .object(at: i) as? Type
        Props: @objc optional, use ?. and ??
        Music: library.searchFor("name", only: .names) — never iterate all tracks
        New bridge: run_agent_script GenerateBridge with args /Applications/App.app

        BRIDGES (import→protocol→bundleID):
        AutomatorBridge→AutomatorApplication→com.apple.Automator
        CalendarBridge→CalendarApplication→com.apple.iCal
        ContactsBridge→ContactsApplication→com.apple.AddressBook
        FinderBridge→FinderApplication→com.apple.finder
        MailBridge→MailApplication→com.apple.mail
        MessagesBridge→MessagesApplication→com.apple.MobileSMS
        MusicBridge→MusicApplication→com.apple.Music
        NotesBridge→NotesApplication→com.apple.Notes
        NumbersBridge→NumbersApplication→com.apple.Numbers
        PagesBridge→PagesApplication→com.apple.Pages
        PhotosBridge→PhotosApplication→com.apple.Photos
        RemindersBridge→RemindersApplication→com.apple.reminders
        SafariBridge→SafariApplication→com.apple.Safari
        SystemEventsBridge→SystemEventsApplication→com.apple.systemevents
        TerminalBridge→TerminalApplication→com.apple.Terminal
        GoogleChromeBridge→GoogleChromeApplication→com.google.Chrome
        FirefoxBridge→FirefoxApplication→org.mozilla.firefox
        KeynoteBridge→KeynoteApplication→com.apple.Keynote
        PreviewBridge→PreviewApplication→com.apple.Preview
        TextEditBridge→TextEditApplication→com.apple.TextEdit
        TVBridge→TVApplication→com.apple.TV
        AgentScriptingBridge→XcodeApplication→com.apple.dt.Xcode
        ImageEventsBridge→ImageEventsApplication→com.apple.systemevents
        ScriptEditorBridge→ScriptEditorApplication→com.apple.ScriptEditor2
        ShortcutsBridge→ShortcutsApplication→com.apple.shortcuts
        QuickTimePlayerBridge→QuickTimePlayerApplication→com.apple.QuickTimePlayerX

        APPLE EVENT QUERY (zero compilation):
        Pass bundle_id + operations array:
        get {key} | iterate {properties, limit} | index {index} | call {method, arg} | filter {predicate}
        Writes blocked by default; set allow_writes=true.

        IMAGE PATHS: Print file paths — UI renders clickable links.

        MCP TOOLS: Your available MCP tools are the mcp_* functions provided to you.
        NEVER call a server's list/tools command to discover tools — your tool list IS the truth.
        Disabled tools are already filtered out. Only use what you see in your function definitions.

        NEVER DO:
        - xcodebuild or swift build via shell → use xcode_build / run_agent_script
        - xcode_build on ~/Documents/Agent/agents/ → use run_agent_script
        - execute_user_command for AX/Automation → use run_agent_script
        """
    }

    // MARK: - Tool Definitions (internal, format-neutral)

    private struct ToolDef {
        let name: String
        let description: String
        let properties: [String: [String: Any]]
        let required: [String]
    }

    nonisolated(unsafe) private static let commonTools: [ToolDef] = [
        // --- Coding Tools ---
        ToolDef(
            name: "read_file",
            description: "Read file contents with line numbers. Use instead of `cat`. Returns numbered lines for easy reference in edit_file.",
            properties: [
                "file_path": ["type": "string", "description": "Absolute path to the file to read"],
                "offset": ["type": "integer", "description": "1-based line number to start from (default 1)"],
                "limit": ["type": "integer", "description": "Max lines to return (default 2000)"],
            ],
            required: ["file_path"]
        ),
        ToolDef(
            name: "write_file",
            description: "Create or overwrite a file. Creates parent dirs automatically. Returns line count only — call read_file after to verify content.",
            properties: [
                "file_path": ["type": "string", "description": "Absolute path to the file to write"],
                "content": ["type": "string", "description": "The full file content to write"],
            ],
            required: ["file_path", "content"]
        ),
        ToolDef(
            name: "edit_file",
            description: "Replace exact text in a file. Use instead of sed/awk. You MUST read_file first. The old_string must be unique unless replace_all is true.",
            properties: [
                "file_path": ["type": "string", "description": "Absolute path to the file to edit"],
                "old_string": ["type": "string", "description": "The exact text to find and replace"],
                "new_string": ["type": "string", "description": "The replacement text"],
                "replace_all": ["type": "boolean", "description": "Replace all occurrences (default false)"],
            ],
            required: ["file_path", "old_string", "new_string"]
        ),
        ToolDef(
            name: "list_files",
            description: "Find files matching a glob pattern. Use instead of `find`. Excludes hidden files and .build directories.",
            properties: [
                "pattern": ["type": "string", "description": "Glob pattern (e.g. \"*.swift\", \"Package.swift\")"],
                "path": ["type": "string", "description": "Directory to search in (default: user home). Always provide a project path for best results."],
            ],
            required: ["pattern"]
        ),
        ToolDef(
            name: "search_files",
            description: "Search file contents by regex pattern. Use instead of `grep`. Returns matching lines with file paths and line numbers.",
            properties: [
                "pattern": ["type": "string", "description": "Regex pattern to search for"],
                "path": ["type": "string", "description": "Directory to search in (default: user home). Always provide a project path for best results."],
                "include": ["type": "string", "description": "File glob filter (e.g. \"*.swift\", \"*.py\")"],
            ],
            required: ["pattern"]
        ),
        // --- Git Tools ---
        ToolDef(
            name: "git_status",
            description: "Show current branch, staged/unstaged changes, and untracked files.",
            properties: [
                "path": ["type": "string", "description": "Repository path (REQUIRED for git operations — provide the project directory)"],
            ],
            required: []
        ),
        ToolDef(
            name: "git_diff",
            description: "Show file changes as a unified diff. Can show staged changes, unstaged changes, or diff against a branch/commit.",
            properties: [
                "path": ["type": "string", "description": "Repository path (REQUIRED for git operations — provide the project directory)"],
                "staged": ["type": "boolean", "description": "Show staged changes only (default false)"],
                "target": ["type": "string", "description": "Branch, commit, or ref to diff against (e.g. \"main\", \"HEAD~3\")"],
            ],
            required: []
        ),
        ToolDef(
            name: "git_log",
            description: "Show recent commit history as one-line summaries.",
            properties: [
                "path": ["type": "string", "description": "Repository path (REQUIRED for git operations — provide the project directory)"],
                "count": ["type": "integer", "description": "Number of commits to show (default 20, max 100)"],
            ],
            required: []
        ),
        ToolDef(
            name: "git_commit",
            description: "Stage files and create a commit. If no files specified, stages all changes.",
            properties: [
                "path": ["type": "string", "description": "Repository path (REQUIRED for git operations — provide the project directory)"],
                "message": ["type": "string", "description": "Commit message"],
                "files": ["type": "array", "items": ["type": "string"] as [String: Any], "description": "Specific files to stage (default: all changes)"] as [String: Any],
            ],
            required: ["message"]
        ),
        ToolDef(
            name: "git_diff_patch",
            description: "Apply a unified diff patch to files in the repository. Use for complex multi-line edits that are easier to express as a patch.",
            properties: [
                "path": ["type": "string", "description": "Repository path (REQUIRED for git operations — provide the project directory)"],
                "patch": ["type": "string", "description": "Unified diff patch content"],
            ],
            required: ["patch"]
        ),
        ToolDef(
            name: "git_branch",
            description: "Create a new git branch, optionally switching to it.",
            properties: [
                "path": ["type": "string", "description": "Repository path (REQUIRED for git operations — provide the project directory)"],
                "name": ["type": "string", "description": "Branch name to create"],
                "checkout": ["type": "boolean", "description": "Switch to the new branch (default true)"],
            ],
            required: ["name"]
        ),
        // --- Core Tools ---
        ToolDef(
            name: "apple_event_query",
            description: "Query any scriptable Mac app dynamically via ScriptingBridge. No compilation needed. Walks the object graph using ObjC dynamic dispatch. Use this FIRST for reading app data (mail, notes, music, safari, calendar, reminders, etc.).",
            properties: [
                "bundle_id": ["type": "string", "description": "App bundle identifier (e.g. com.apple.Music)"],
                "operations": [
                    "type": "array",
                    "description": "Array of operations to execute sequentially. Each has an 'action' key.",
                    "items": [
                        "type": "object",
                        "properties": [
                            "action": ["type": "string", "description": "One of: get, iterate, index, call, filter"],
                            "key": ["type": "string", "description": "Property key for 'get'"],
                            "properties": ["type": "array", "items": ["type": "string"], "description": "Properties to read for 'iterate'"],
                            "limit": ["type": "integer", "description": "Max items for 'iterate' (default 50)"],
                            "index": ["type": "integer", "description": "Array index for 'index'"],
                            "method": ["type": "string", "description": "Method name for 'call'"],
                            "arg": ["type": "string", "description": "Optional argument for 'call'"],
                            "predicate": ["type": "string", "description": "NSPredicate format string for 'filter'"],
                        ] as [String: Any],
                        "required": ["action"],
                    ] as [String: Any],
                ] as [String: Any],
                "allow_writes": ["type": "boolean", "description": "Allow destructive operations (delete, close, move, etc.). Default false."],
            ],
            required: ["bundle_id", "operations"]
        ),
        ToolDef(
            name: "execute_user_command",
            description: "Execute a shell command as the current user (no root). Use this for most tasks: git, builds, scripts, homebrew, etc.",
            properties: [
                "command": ["type": "string", "description": "The bash command to execute as the current user"],
            ],
            required: ["command"]
        ),
        ToolDef(
            name: "execute_command",
            description: "Execute a shell command with ROOT privileges via the privileged daemon. Only use when root is required: system packages, /System or /Library modifications, disk operations, launchd services, or changing ownership outside user home.",
            properties: [
                "command": ["type": "string", "description": "The bash command to execute as root"],
            ],
            required: ["command"]
        ),
        ToolDef(
            name: "task_complete",
            description: "Signal that the task has been completed. Always call this when done.",
            properties: [
                "summary": ["type": "string", "description": "Brief summary of what was accomplished"],
            ],
            required: ["summary"]
        ),
        // --- Accessibility Tools ---
        ToolDef(
            name: "ax_list_windows",
            description: "List all visible windows from all applications with their positions and sizes. Returns JSON array with window ID, owner PID, owner name, window name, and bounds.",
            properties: [
                "limit": ["type": "integer", "description": "Maximum number of windows to return (default 50)"],
            ],
            required: []
        ),
        ToolDef(
            name: "ax_inspect_element",
            description: "Inspect accessibility element at a screen coordinate. Returns the accessibility hierarchy for the element at position (x, y).",
            properties: [
                "x": ["type": "number", "description": "Screen X coordinate"],
                "y": ["type": "number", "description": "Screen Y coordinate"],
                "depth": ["type": "integer", "description": "How deep to traverse the hierarchy (default 3)"],
            ],
            required: ["x", "y"]
        ),
        ToolDef(
            name: "ax_get_properties",
            description: "Get all properties of an accessibility element. Can find by role/title or by screen position.",
            properties: [
                "role": ["type": "string", "description": "Accessibility role to find (e.g., 'AXButton', 'AXTextField')"],
                "title": ["type": "string", "description": "Title or name to match (partial match)"],
                "appBundleId": ["type": "string", "description": "Optional bundle ID to search within a specific app"],
                "x": ["type": "number", "description": "Screen X coordinate for position-based lookup"],
                "y": ["type": "number", "description": "Screen Y coordinate for position-based lookup"],
            ],
            required: []
        ),
        ToolDef(
            name: "ax_perform_action",
            description: "Perform an accessibility action on an element. SECURITY: Interaction actions (click, press) require allowWrites=true. Password fields are always blocked.",
            properties: [
                "role": ["type": "string", "description": "Accessibility role to find"],
                "title": ["type": "string", "description": "Title to match"],
                "appBundleId": ["type": "string", "description": "Bundle ID of the target app"],
                "x": ["type": "number", "description": "Screen X coordinate for position-based lookup"],
                "y": ["type": "number", "description": "Screen Y coordinate for position-based lookup"],
                "action": ["type": "string", "description": "Accessibility action to perform (e.g., 'AXPress', 'AXConfirm')"],
                "allowWrites": ["type": "boolean", "description": "Allow interaction actions (default false)"],
            ],
            required: ["action"]
        ),
        ToolDef(
            name: "ax_check_permission",
            description: "Check if Accessibility permission is granted to Agent.",
            properties: [:],
            required: []
        ),
        ToolDef(
            name: "ax_request_permission",
            description: "Request Accessibility permission. Shows the macOS system prompt for the user to approve.",
            properties: [:],
            required: []
        ),
        // --- Accessibility Input Simulation (Phase 2) ---
        ToolDef(
            name: "ax_type_text",
            description: "Simulate typing text at the current cursor position or at specific coordinates. Uses CGEvent keyboard simulation.",
            properties: [
                "text": ["type": "string", "description": "Text to type"],
                "x": ["type": "number", "description": "Optional X coordinate to click first before typing"],
                "y": ["type": "number", "description": "Optional Y coordinate to click first before typing"],
            ],
            required: ["text"]
        ),
        ToolDef(
            name: "ax_click",
            description: "Simulate a mouse click at screen coordinates.",
            properties: [
                "x": ["type": "number", "description": "Screen X coordinate (required)"],
                "y": ["type": "number", "description": "Screen Y coordinate (required)"],
                "button": ["type": "string", "description": "Mouse button: 'left' (default), 'right', or 'middle'"],
                "clicks": ["type": "integer", "description": "Number of clicks: 1 (default) or 2 for double-click"],
            ],
            required: ["x", "y"]
        ),
        ToolDef(
            name: "ax_scroll",
            description: "Simulate scroll wheel at screen coordinates.",
            properties: [
                "x": ["type": "number", "description": "Screen X coordinate"],
                "y": ["type": "number", "description": "Screen Y coordinate"],
                "deltaX": ["type": "integer", "description": "Horizontal scroll amount (positive = right, negative = left)"],
                "deltaY": ["type": "integer", "description": "Vertical scroll amount (positive = down, negative = up)"],
            ],
            required: ["x", "y"]
        ),
        ToolDef(
            name: "ax_press_key",
            description: "Simulate pressing a key with optional modifiers (Cmd, Option, Control, Shift).",
            properties: [
                "keyCode": ["type": "integer", "description": "macOS virtual key code (e.g., 36=Return, 48=Tab, 51=Delete, 53=Escape, 123-126=Arrow keys)"],
                "modifiers": ["type": "array", "description": "Array of modifier keys: 'command', 'option', 'control', 'shift'", "items": ["type": "string"]],
            ],
            required: ["keyCode"]
        ),
        // --- Accessibility Screenshots (Phase 4) ---
        ToolDef(
            name: "ax_screenshot",
            description: "Capture a screenshot of a screen region or specific window. Requires Screen Recording permission. Returns the path to the saved PNG file.",
            properties: [
                "x": ["type": "number", "description": "X coordinate of region (optional, required for region capture)"],
                "y": ["type": "number", "description": "Y coordinate of region (optional, required for region capture)"],
                "width": ["type": "number", "description": "Width of region (optional, required for region capture)"],
                "height": ["type": "number", "description": "Height of region (optional, required for region capture)"],
                "windowId": ["type": "integer", "description": "Window ID to capture (optional, from ax_list_windows)"],
            ],
            required: []
        ),
        // --- Accessibility Audit Log (Phase 5) ---
        ToolDef(
            name: "ax_get_audit_log",
            description: "Get recent accessibility audit log entries. Shows recent accessibility operations performed by the agent.",
            properties: [
                "limit": ["type": "integer", "description": "Maximum number of entries to return (default 50)"],
            ],
            required: []
        ),
        // --- Script Management ---
        ToolDef(
            name: "list_agent_scripts",
            description: "List all Swift automation scripts in ~/Documents/Agent/agents/",
            properties: [:],
            required: []
        ),
        ToolDef(
            name: "read_agent_script",
            description: "Read the source code of a Swift automation script.",
            properties: [
                "name": ["type": "string", "description": "Script name (with or without .swift)"],
            ],
            required: ["name"]
        ),
        ToolDef(
            name: "create_agent_script",
            description: "Create a new Swift automation script in ~/Documents/Agent/agents/",
            properties: [
                "name": ["type": "string", "description": "Script filename (with or without .swift)"],
                "content": ["type": "string", "description": "Swift source code"],
            ],
            required: ["name", "content"]
        ),
        ToolDef(
            name: "update_agent_script",
            description: "Update an existing Swift automation script.",
            properties: [
                "name": ["type": "string", "description": "Script filename"],
                "content": ["type": "string", "description": "New Swift source code"],
            ],
            required: ["name", "content"]
        ),
        ToolDef(
            name: "run_agent_script",
            description: "Compile and run a Swift dylib script from ~/Documents/Agent/agents/. Output is streamed live to the activity log — do NOT repeat or summarize stdout output. For structured data, write a JSON input file first via execute_user_command, then run the script.",
            properties: [
                "name": ["type": "string", "description": "Script filename (without .swift)"],
                "arguments": ["type": "string", "description": "Simple string passed via AGENT_SCRIPT_ARGS env var. For complex data, use JSON files instead."],
            ],
            required: ["name"]
        ),
        ToolDef(
            name: "delete_agent_script",
            description: "Delete a Swift automation script.",
            properties: [
                "name": ["type": "string", "description": "Script filename"],
            ],
            required: ["name"]
        ),
        // --- Xcode ---
        ToolDef(
            name: "xcode_build",
            description: "Build an Xcode project or workspace via ScriptingBridge. Blocks until build completes. Returns errors/warnings in file:line:col format with code snippets for context.",
            properties: [
                "project_path": ["type": "string", "description": "Path to .xcodeproj or .xcworkspace"],
            ],
            required: ["project_path"]
        ),
        ToolDef(
            name: "xcode_run",
            description: "Build then run an Xcode project via ScriptingBridge. Builds first — only runs if clean. Returns errors if build fails.",
            properties: [
                "project_path": ["type": "string", "description": "Path to .xcodeproj or .xcworkspace"],
            ],
            required: ["project_path"]
        ),
        ToolDef(
            name: "xcode_list_projects",
            description: "List all open Xcode projects and workspaces with numbered indices. Use the number with xcode_select_project to choose one.",
            properties: [:],
            required: []
        ),
        ToolDef(
            name: "xcode_select_project",
            description: "Select an open Xcode project by its number from xcode_list_projects. Returns the project path for use with xcode_build/xcode_run.",
            properties: [
                "number": ["type": "integer", "description": "Project number from the list (1-based)"],
            ],
            required: ["number"]
        ),
        ToolDef(
            name: "xcode_grant_permission",
            description: "Grant macOS Automation permission so the agent can control Xcode via ScriptingBridge. Run this once before using xcode_build or xcode_run.",
            properties: [:],
            required: []
        ),
    ]

    // MARK: - Claude (Anthropic) Format

    /// Convert a ToolDef to Anthropic's tool schema.
    static func claudeTool(name: String, description: String, properties: [String: Any], required: [String]) -> [String: Any] {
        [
            "name": name,
            "description": description,
            "input_schema": [
                "type": "object",
                "properties": properties,
                "required": required,
            ] as [String: Any],
        ]
    }

    /// Sanitize an MCP tool name to alphanumeric, underscore, and hyphen only.
    private static func sanitizeToolName(_ name: String) -> String {
        String(name.unicodeScalars.filter { CharacterSet.alphanumerics.contains($0) || $0 == "_" || $0 == "-" }.prefix(128))
    }

    /// Sanitize an MCP tool description: collapse newlines, cap length.
    private static func sanitizeDescription(_ desc: String, maxLength: Int = 1024) -> String {
        let cleaned = desc
            .replacingOccurrences(of: "\r\n", with: " ")
            .replacingOccurrences(of: "\n", with: " ")
            .replacingOccurrences(of: "\r", with: " ")
        return String(cleaned.prefix(maxLength))
    }

    /// Recursively remove NSNull values and ensure schema validity
    private static func sanitizeSchema(_ value: Any) -> Any {
        if let dict = value as? [String: Any] {
            // Filter out NSNull values and sanitize recursively
            var result: [String: Any] = [:]
            for (key, val) in dict {
                if !(val is NSNull) {
                    result[key] = sanitizeSchema(val)
                }
            }
            // Ensure "properties" is always an object if present
            if result["properties"] == nil {
                result["properties"] = [:] as [String: Any]
            }
            return result
        } else if let arr = value as? [Any] {
            return arr.map { sanitizeSchema($0) }
        } else if value is NSNull {
            // Replace NSNull with empty object for schema fields, or empty string for others
            return "" as Any
        }
        return value
    }

    /// All common tools + MCP tools in Claude/Anthropic format.
    @MainActor static var claudeFormat: [[String: Any]] {
        var tools = commonTools.map { tool in
            claudeTool(name: tool.name, description: tool.description,
                       properties: tool.properties, required: tool.required)
        }
        let mcpService = MCPService.shared
        for tool in mcpService.discoveredTools where mcpService.isToolEnabled(serverName: tool.serverName, toolName: tool.name) {
            let safeName = sanitizeToolName("mcp_\(tool.serverName)_\(tool.name)")
            let safeDesc = sanitizeDescription("[MCP:\(tool.serverName)] \(tool.description)")
            let rawSchema = (try? JSONSerialization.jsonObject(with: Data(tool.inputSchemaJSON.utf8))) as? [String: Any]
            let schema = rawSchema.map { sanitizeSchema($0) as? [String: Any] } ?? nil
            let validSchema: [String: Any]
            if let s = schema, !s.isEmpty {
                validSchema = s
            } else {
                validSchema = ["type": "object", "properties": [:] as [String: Any]]
            }
            tools.append([
                "name": safeName,
                "description": safeDesc,
                "input_schema": validSchema,
            ] as [String: Any])
        }
        return tools
    }

    // MARK: - Ollama (OpenAI) Format

    /// Convert a ToolDef to OpenAI/Ollama tool schema.
    static func ollamaTool(name: String, description: String, properties: [String: Any], required: [String]) -> [String: Any] {
        [
            "type": "function",
            "function": [
                "name": name,
                "description": description,
                "parameters": [
                    "type": "object",
                    "properties": properties,
                    "required": required,
                ] as [String: Any],
            ] as [String: Any],
        ]
    }

    /// Tools only available for Ollama providers (client-side web search via Tavily).
    nonisolated(unsafe) private static let ollamaOnlyTools: [ToolDef] = [
        ToolDef(
            name: "web_search",
            description: "Search the web for current information. Returns relevant web page titles, URLs, and content snippets. Use when you need up-to-date information or facts you're unsure about.",
            properties: [
                "query": ["type": "string", "description": "The search query"],
            ],
            required: ["query"]
        ),
    ]

    /// All common tools + Ollama-specific tools + MCP tools in Ollama/OpenAI format.
    @MainActor static var ollamaFormat: [[String: Any]] {
        var tools = (commonTools + ollamaOnlyTools).map { tool in
            ollamaTool(name: tool.name, description: tool.description,
                       properties: tool.properties, required: tool.required)
        }
        let mcpService = MCPService.shared
        for tool in mcpService.discoveredTools where mcpService.isToolEnabled(serverName: tool.serverName, toolName: tool.name) {
            let safeName = sanitizeToolName("mcp_\(tool.serverName)_\(tool.name)")
            let safeDesc = sanitizeDescription("[MCP:\(tool.serverName)] \(tool.description)")
            let rawSchema = (try? JSONSerialization.jsonObject(with: Data(tool.inputSchemaJSON.utf8))) as? [String: Any]
            let schema = rawSchema.map { sanitizeSchema($0) as? [String: Any] } ?? nil
            let validSchema: [String: Any]
            if let s = schema, !s.isEmpty {
                validSchema = s
            } else {
                validSchema = ["type": "object", "properties": [:] as [String: Any]]
            }
            tools.append([
                "type": "function",
                "function": [
                    "name": safeName,
                    "description": safeDesc,
                    "parameters": validSchema,
                ] as [String: Any],
            ] as [String: Any])
        }
        return tools
    }
}
